-- Seed system themes
INSERT INTO "themes" ("id", "name", "description", "is_default", "is_system_theme", "config", "preview_image_url", "updated_at")
VALUES
  ('classic-elegance', 'Classic Elegance', 'Timeless and sophisticated with traditional elegance', true, true, '{"colors":{"primary":"#8B7355","secondary":"#C9B8A8","accent":"#D4AF37","background":"#FDFBF7","text":"#2C2416","textSecondary":"#5C5347","border":"#E8DFD4"},"fonts":{"heading":"Playfair Display, serif","body":"Lora, serif"},"styles":{"buttonRadius":"4px","cardShadow":"0 2px 8px rgba(139, 115, 85, 0.15)","spacing":"1rem","borderRadius":"4px"}}'::jsonb, NULL, NOW()),
  ('garden-romance', 'Garden Romance', 'Soft florals and natural beauty for outdoor celebrations', false, true, '{"colors":{"primary":"#7C9473","secondary":"#B8C5B3","accent":"#E8A5A5","background":"#F9FBF7","text":"#2C3E2A","textSecondary":"#5A6E56","border":"#D9E3D6"},"fonts":{"heading":"Cormorant Garamond, serif","body":"Quicksand, sans-serif"},"styles":{"buttonRadius":"12px","cardShadow":"0 4px 12px rgba(124, 148, 115, 0.12)","spacing":"1.25rem","borderRadius":"12px"},"images":{"background":"/themes/garden/floral-pattern.svg"}}'::jsonb, NULL, NOW()),
  ('modern-minimal', 'Modern Minimal', 'Clean lines and contemporary design', false, true, '{"colors":{"primary":"#2D3748","secondary":"#718096","accent":"#4299E1","background":"#FFFFFF","text":"#1A202C","textSecondary":"#718096","border":"#E2E8F0"},"fonts":{"heading":"Inter, sans-serif","body":"Inter, sans-serif","weight":{"normal":400,"bold":600,"heading":700}},"styles":{"buttonRadius":"6px","cardShadow":"0 1px 3px rgba(0, 0, 0, 0.1)","spacing":"1rem","borderRadius":"6px","borderWidth":"1px"}}'::jsonb, NULL, NOW()),
  ('rustic-charm', 'Rustic Charm', 'Warm and cozy with natural textures', false, true, '{"colors":{"primary":"#8B4513","secondary":"#D2691E","accent":"#CD853F","background":"#FFF8F0","text":"#3E2723","textSecondary":"#6D4C41","border":"#D7CCC8"},"fonts":{"heading":"Merriweather, serif","body":"Open Sans, sans-serif"},"styles":{"buttonRadius":"8px","cardShadow":"0 3px 10px rgba(139, 69, 19, 0.2)","spacing":"1rem","borderRadius":"8px","borderWidth":"2px"},"images":{"background":"/themes/rustic/wood-texture.jpg"}}'::jsonb, NULL, NOW()),
  ('beach-breeze', 'Beach Breeze', 'Light and airy with coastal vibes', false, true, '{"colors":{"primary":"#0891B2","secondary":"#06B6D4","accent":"#F59E0B","background":"#F0FDFA","text":"#164E63","textSecondary":"#0E7490","border":"#CFFAFE"},"fonts":{"heading":"Poppins, sans-serif","body":"Nunito, sans-serif"},"styles":{"buttonRadius":"9999px","cardShadow":"0 4px 14px rgba(8, 145, 178, 0.15)","spacing":"1rem","borderRadius":"16px"},"images":{"background":"/themes/beach/waves-pattern.svg"}}'::jsonb, NULL, NOW()),
  ('garden-birds', 'Garden Birds', 'Enchanting envelope reveal with botanical elegance', false, true, '{"colors":{"primary":"#6B8E6F","secondary":"#A8C5A4","accent":"#E8B86D","background":"#FAF9F5","text":"#3A4F3C","textSecondary":"#6E7F70","border":"#D9E3D6"},"fonts":{"heading":"Crimson Text, serif","body":"Libre Baskerville, serif"},"styles":{"buttonRadius":"20px","cardShadow":"0 6px 20px rgba(107, 142, 111, 0.15)","spacing":"1.25rem","borderRadius":"15px"},"images":{"background":"/themes/garden-birds/botanical-pattern.svg"}}'::jsonb, NULL, NOW())
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "config" = EXCLUDED."config",
  "preview_image_url" = EXCLUDED."preview_image_url",
  "updated_at" = NOW();
