-- Add MESSAGE_DELIVERED, MESSAGE_READ, MESSAGE_FAILED to EventType enum
ALTER TYPE "EventType" ADD VALUE 'MESSAGE_DELIVERED';
ALTER TYPE "EventType" ADD VALUE 'MESSAGE_READ';
ALTER TYPE "EventType" ADD VALUE 'MESSAGE_FAILED';
