/**
 * API endpoint for exporting providers library to PDF
 */

import { NextRequest, NextResponse } from 'next/server';
import { renderToBuffer, Document, Page, Text, View, StyleSheet, Image as PDFImage } from '@react-pdf/renderer';
import { getTranslations } from 'next-intl/server';
import { getLocale } from 'next-intl/server';
import React from 'react';
import path from 'path';
import { readFile, access } from 'fs/promises';

async function resolveImageForPdf(url: string, maxPx = 600): Promise<string | null> {
  try {
    let rawBuf: Buffer;

    if (url.startsWith('http://') || url.startsWith('https://')) {
      const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
      if (!res.ok) {
        console.warn(`[pdf-image] HTTP ${res.status} for ${url}`);
        return null;
      }
      rawBuf = Buffer.from(await res.arrayBuffer());
    } else {
      const rel = url.startsWith('/') ? url.slice(1) : url;
      const absPath = path.join(process.cwd(), 'public', rel);
      try { await access(absPath); } catch {
        console.warn(`[pdf-image] Local file not found: ${absPath}`);
        return null;
      }
      rawBuf = await readFile(absPath);
    }

    if (!rawBuf.length) return null;

    const sharp = (await import('sharp')).default;
    const resized = await sharp(rawBuf)
      .resize(maxPx, maxPx, { fit: 'inside', withoutEnlargement: true })
      .flatten({ background: '#ffffff' })
      .jpeg({ quality: 95 })
      .toBuffer();

    return `data:image/jpeg;base64,${resized.toString('base64')}`;
  } catch (err) {
    console.warn(`[pdf-image] Failed to resolve ${url}:`, err);
    return null;
  }
}

export async function POST(req: NextRequest) {
  try {
    const { categories, providers } = await req.json();
    const locale = await getLocale() as 'es' | 'en' | 'fr' | 'it' | 'de';
    const t = await getTranslations({ locale, namespace: 'planner.providers' });

    const logoUrl = await resolveImageForPdf('/images/nupci.png', 600);

    const footerMessages: Record<'es' | 'en' | 'fr' | 'it' | 'de', string> = {
      es: 'Generado por nupci',
      en: 'Generated by nupci',
      fr: 'Généré par nupci',
      it: 'Generato da nupci',
      de: 'Generiert von nupci',
    };

    const footer = footerMessages[locale] || 'Generated by nupci';

    const styles = StyleSheet.create({
      page: {
        padding: 40,
        fontSize: 10,
        fontFamily: 'Helvetica',
      },
      header: {
        marginBottom: 30,
        borderBottomWidth: 2,
        borderBottomColor: '#e5e7eb',
        paddingBottom: 15,
        display: 'flex',
        flexDirection: 'row',
      },
      headerContent: {
        flex: 1,
      },
      logo: {
        width: 60,
        height: 60,
        marginRight: 20,
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 5,
      },
      subtitle: {
        fontSize: 12,
        color: '#6b7280',
      },
      section: {
        marginBottom: 25,
      },
      sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 10,
        backgroundColor: '#f3f4f6',
        padding: 8,
      },
      tableHeader: {
        backgroundColor: '#374151',
        color: '#ffffff',
        fontWeight: 'bold',
      },
      tableRow: {
        display: 'flex',
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
      },
      tableRowAlt: {
        backgroundColor: '#f9fafb',
      },
      tableCell: {
        padding: 8,
        fontSize: 9,
        flex: 1,
      },
      footer: {
        marginTop: 40,
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        textAlign: 'center' as const,
        color: '#9ca3af',
        fontSize: 9,
      },
    });

    const tableRows = providers.map((provider: any, index: number) => {
      const category = categories.find((c: any) => c.id === provider.category_id);
      const rowStyle = index % 2 === 1 ? [styles.tableRow, styles.tableRowAlt] : [styles.tableRow];
      return React.createElement(View, { key: provider.id, style: rowStyle },
        React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
          React.createElement(Text, null, category?.name || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
          React.createElement(Text, null, provider.name || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
          React.createElement(Text, null, provider.contact_name || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
          React.createElement(Text, null, provider.email || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
          React.createElement(Text, null, provider.phone || '')
        )
      );
    });

    const PDFDoc = React.createElement(Document, null,
      React.createElement(Page, { size: 'A4', style: styles.page },
        logoUrl
          ? React.createElement(View, { style: styles.header },
              React.createElement(PDFImage, { src: logoUrl, style: styles.logo }),
              React.createElement(View, { style: styles.headerContent },
                React.createElement(Text, { style: styles.title }, t('exportLibrary') || 'Providers Library'),
                React.createElement(Text, { style: styles.subtitle }, new Date().toLocaleDateString())
              )
            )
          : React.createElement(View, { style: styles.header },
              React.createElement(Text, { style: styles.title }, t('exportLibrary') || 'Providers Library'),
              React.createElement(Text, { style: styles.subtitle }, new Date().toLocaleDateString())
            ),

        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, t('exportLibrary') || 'Providers Library'),

          React.createElement(View, { style: { ...styles.section, marginBottom: 0 } },
            React.createElement(View, { style: [styles.tableRow, styles.tableHeader] },
              React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
                React.createElement(Text, null, t('category') || 'Category')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
                React.createElement(Text, null, t('provider') || 'Provider')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
                React.createElement(Text, null, t('contactPerson') || 'Contact')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
                React.createElement(Text, null, t('email') || 'Email')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
                React.createElement(Text, null, t('phone') || 'Phone')
              )
            ),
            ...tableRows
          )
        ),

        React.createElement(View, { style: styles.footer },
          React.createElement(Text, null, footer)
        )
      )
    );

    const buffer = await renderToBuffer(PDFDoc);

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="providers-library-${new Date().toISOString().split('T')[0]}.pdf"`,
      },
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
