/**
 * API endpoint for exporting wedding providers to PDF
 */

import { NextRequest, NextResponse } from 'next/server';
import { renderToBuffer, Document, Page, Text, View, StyleSheet, Image as PDFImage } from '@react-pdf/renderer';
import { getTranslations } from 'next-intl/server';
import { getLocale } from 'next-intl/server';
import React from 'react';
import path from 'path';
import { readFile, access } from 'fs/promises';
import { prisma } from '@/lib/db/prisma';

async function resolveImageForPdf(url: string, maxPx = 600): Promise<string | null> {
  try {
    const MAX_IMAGE_SIZE = 5 * 1024 * 1024; // 5MB limit
    let rawBuf: Buffer;

    if (url.startsWith('http://') || url.startsWith('https://')) {
      const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
      if (!res.ok) return null;
      const arrayBuf = await res.arrayBuffer();
      if (arrayBuf.byteLength > MAX_IMAGE_SIZE) return null;
      rawBuf = Buffer.from(arrayBuf);
    } else {
      const rel = url.startsWith('/') ? url.slice(1) : url;
      const absPath = path.join(process.cwd(), 'public', rel);
      try { await access(absPath); } catch { return null; }
      rawBuf = await readFile(absPath);
      if (rawBuf.length > MAX_IMAGE_SIZE) return null;
    }

    if (!rawBuf.length) return null;

    const sharp = (await import('sharp')).default;
    const resized = await sharp(rawBuf)
      .resize(maxPx, maxPx, { fit: 'inside', withoutEnlargement: true })
      .flatten({ background: '#ffffff' })
      .jpeg({ quality: 95 })
      .toBuffer();

    return `data:image/jpeg;base64,${resized.toString('base64')}`;
  } catch {
    return null;
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { weddingProviders, plannedGuests, weddingId } = body;

    // Input validation
    if (!Array.isArray(weddingProviders)) {
      return NextResponse.json(
        { error: 'weddingProviders must be an array' },
        { status: 400 }
      );
    }

    if (typeof plannedGuests !== 'number' || plannedGuests < 0) {
      return NextResponse.json(
        { error: 'plannedGuests must be a non-negative number' },
        { status: 400 }
      );
    }

    if (weddingId && typeof weddingId !== 'string') {
      return NextResponse.json(
        { error: 'weddingId must be a string' },
        { status: 400 }
      );
    }

    const locale = await getLocale() as 'es' | 'en' | 'fr' | 'it' | 'de';
    const t = await getTranslations({ locale, namespace: 'planner.providers' });

    // Fetch planner logo from database
    let plannerLogoUrl: string | null = null;
    if (weddingId) {
      const wedding = await prisma.wedding.findUnique({
        where: { id: weddingId },
        select: { planner: { select: { logo_url: true } } },
      });
      plannerLogoUrl = wedding?.planner?.logo_url ?? null;
    }

    const logoUrl = plannerLogoUrl ? await resolveImageForPdf(plannerLogoUrl, 600) : null;

    const footerMessages: Record<'es' | 'en' | 'fr' | 'it' | 'de', string> = {
      es: 'Generado por nupci',
      en: 'Generated by nupci',
      fr: 'Généré par nupci',
      it: 'Generato da nupci',
      de: 'Generiert von nupci',
    };

    const footer = footerMessages[locale] || 'Generated by nupci';

    const titleMessages: Record<'es' | 'en' | 'fr' | 'it' | 'de', string> = {
      es: 'Proveedores',
      en: 'Providers',
      fr: 'Fournisseurs',
      it: 'Fornitori',
      de: 'Anbieter',
    };

    const title = titleMessages[locale] || 'Providers';

    const getProjected = (wp: any): number => {
      const b = wp.budgeted_price ? Number(wp.budgeted_price) : 0;
      if (!b) return 0;
      return wp.category.price_type === 'PER_PERSON' && plannedGuests ? b * plannedGuests : b;
    };

    const getRealTotal = (wp: any): number => {
      const r = wp.total_price ? Number(wp.total_price) : 0;
      if (!r) return 0;
      return wp.category.price_type === 'PER_PERSON' && plannedGuests ? r * plannedGuests : r;
    };

    const localeMap: Record<'es' | 'en' | 'fr' | 'it' | 'de', string> = {
      es: 'es-ES',
      en: 'en-US',
      fr: 'fr-FR',
      it: 'it-IT',
      de: 'de-DE',
    };

    const formatCurrency = (value: number): string => {
      return new Intl.NumberFormat(localeMap[locale], {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      }).format(value);
    };

    let totalBudgeted = 0;
    let totalReal = 0;
    let totalPaid = 0;

    for (const wp of weddingProviders) {
      const paid = (Array.isArray(wp.payments) ? wp.payments : []).reduce((sum: number, p: any) => sum + Number(p.amount), 0);
      totalBudgeted += getProjected(wp);
      totalReal += getRealTotal(wp);
      totalPaid += paid;
    }

    const styles = StyleSheet.create({
      page: {
        padding: 40,
        fontSize: 10,
        fontFamily: 'Helvetica',
      },
      header: {
        marginBottom: 30,
        borderBottomWidth: 2,
        borderBottomColor: '#e5e7eb',
        paddingBottom: 15,
        display: 'flex',
        flexDirection: 'row',
      },
      headerContent: {
        flex: 1,
      },
      logo: {
        width: 100,
        height: 100,
        marginRight: 30,
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 5,
      },
      subtitle: {
        fontSize: 12,
        color: '#6b7280',
      },
      section: {
        marginBottom: 25,
      },
      sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 10,
        backgroundColor: '#f3f4f6',
        padding: 8,
      },
      tableHeader: {
        backgroundColor: '#374151',
        color: '#ffffff',
        fontWeight: 'bold',
      },
      tableRow: {
        display: 'flex',
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
      },
      tableRowAlt: {
        backgroundColor: '#f9fafb',
      },
      tableCell: {
        padding: 8,
        fontSize: 9,
        flex: 1,
      },
      tableCellRight: {
        textAlign: 'right' as const,
      },
      totalsRow: {
        fontWeight: 'bold',
        backgroundColor: '#e0e7ff',
        color: '#1e1b4b',
      },
      footer: {
        marginTop: 40,
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        textAlign: 'center' as const,
        color: '#9ca3af',
        fontSize: 9,
      },
    });

    const tableRows = weddingProviders.map((wp: any, index: number) => {
      const paid = (Array.isArray(wp.payments) ? wp.payments : []).reduce((sum: number, p: any) => sum + Number(p.amount), 0);
      const total = getRealTotal(wp);
      const projected = getProjected(wp);
      const pending = total - paid;
      const rowStyle = index % 2 === 1 ? [styles.tableRow, styles.tableRowAlt] : [styles.tableRow];

      return React.createElement(View, { key: wp.id, style: rowStyle },
        React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
          React.createElement(Text, null, wp.category.name)
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
          React.createElement(Text, null, wp.name || wp.provider?.name || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
          React.createElement(Text, null, wp.contact_name || wp.provider?.contact_name || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
          React.createElement(Text, null, wp.budgeted_price ? formatCurrency(Number(wp.budgeted_price)) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
          React.createElement(Text, null, projected > 0 ? formatCurrency(projected) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
          React.createElement(Text, null, total > 0 ? formatCurrency(total) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
          React.createElement(Text, null, paid > 0 ? formatCurrency(paid) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
          React.createElement(Text, null, pending > 0 ? formatCurrency(pending) : '—')
        )
      );
    });

    const PDFDoc = React.createElement(Document, null,
      React.createElement(Page, { size: 'A4', style: styles.page },
        logoUrl
          ? React.createElement(View, { style: styles.header },
              React.createElement(PDFImage, { src: logoUrl, style: styles.logo }),
              React.createElement(View, { style: styles.headerContent },
                React.createElement(Text, { style: styles.title }, title),
                React.createElement(Text, { style: styles.subtitle }, new Date().toLocaleDateString(localeMap[locale])),
                plannedGuests > 0 && React.createElement(Text, { style: styles.subtitle }, `${t('plannedGuests') || 'Planned Guests'}: ${plannedGuests}`)
              )
            )
          : React.createElement(View, { style: styles.header },
              React.createElement(Text, { style: styles.title }, title),
              React.createElement(Text, { style: styles.subtitle }, new Date().toLocaleDateString(localeMap[locale])),
              plannedGuests > 0 && React.createElement(Text, { style: styles.subtitle }, `${t('plannedGuests') || 'Planned Guests'}: ${plannedGuests}`)
            ),

        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, title),

          React.createElement(View, { style: { ...styles.section, marginBottom: 0 } },
            React.createElement(View, { style: [styles.tableRow, styles.tableHeader] },
              React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
                React.createElement(Text, null, t('category') || 'Category')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
                React.createElement(Text, null, t('provider') || 'Provider')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
                React.createElement(Text, null, t('contactPerson') || 'Contact')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('budgetedPrice') || 'Budgeted')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('projectedTotal') || 'Projected')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('totalPrice') || 'Total')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('paid') || 'Paid')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('pending') || 'Pending')
              )
            ),
            ...tableRows,
            React.createElement(View, { style: [styles.tableRow, styles.totalsRow] },
              React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
                React.createElement(Text, null, t('totals') || 'Totals')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
                React.createElement(Text, null, '')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
                React.createElement(Text, null, '')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, '')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalBudgeted))
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalReal))
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalPaid))
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalReal - totalPaid))
              )
            )
          )
        ),

        React.createElement(View, { style: styles.footer },
          React.createElement(Text, null, footer)
        )
      )
    );

    const buffer = await renderToBuffer(PDFDoc);

    // Generate unique filename with timestamp
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];
    const timeStr = now.toISOString().split('T')[1].split('.')[0].replace(/:/g, '');
    const filename = `wedding-providers-${dateStr}-${timeStr}.pdf`;

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
