/**
 * API endpoint for exporting wedding providers to PDF
 */

import { NextRequest, NextResponse } from 'next/server';
import { renderToBuffer, Document, Page, Text, View, StyleSheet, Image as PDFImage } from '@react-pdf/renderer';
import { getTranslations } from 'next-intl/server';
import { getLocale } from 'next-intl/server';
import React from 'react';
import path from 'path';
import { readFile, access } from 'fs/promises';

async function resolveImageForPdf(url: string, maxPx = 600): Promise<string | null> {
  try {
    let rawBuf: Buffer;

    if (url.startsWith('http://') || url.startsWith('https://')) {
      const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
      if (!res.ok) return null;
      rawBuf = Buffer.from(await res.arrayBuffer());
    } else {
      const rel = url.startsWith('/') ? url.slice(1) : url;
      const absPath = path.join(process.cwd(), 'public', rel);
      try { await access(absPath); } catch { return null; }
      rawBuf = await readFile(absPath);
    }

    if (!rawBuf.length) return null;

    const sharp = (await import('sharp')).default;
    const resized = await sharp(rawBuf)
      .resize(maxPx, maxPx, { fit: 'inside', withoutEnlargement: true })
      .flatten({ background: '#ffffff' })
      .jpeg({ quality: 95 })
      .toBuffer();

    return `data:image/jpeg;base64,${resized.toString('base64')}`;
  } catch {
    return null;
  }
}

export async function POST(req: NextRequest) {
  try {
    const { weddingProviders, plannedGuests } = await req.json();
    const locale = await getLocale() as 'es' | 'en' | 'fr' | 'it' | 'de';
    const t = await getTranslations({ locale, namespace: 'planner.providers' });

    const logoUrl = await resolveImageForPdf('/images/nupci.png', 600);

    const footerMessages: Record<'es' | 'en' | 'fr' | 'it' | 'de', string> = {
      es: 'Generado por nupci',
      en: 'Generated by nupci',
      fr: 'Généré par nupci',
      it: 'Generato da nupci',
      de: 'Generiert von nupci',
    };

    const footer = footerMessages[locale] || 'Generated by nupci';

    const getProjected = (wp: any): number => {
      const b = wp.budgeted_price ? Number(wp.budgeted_price) : 0;
      if (!b) return 0;
      return wp.category.price_type === 'PER_PERSON' && plannedGuests ? b * plannedGuests : b;
    };

    const getRealTotal = (wp: any): number => {
      const r = wp.total_price ? Number(wp.total_price) : 0;
      if (!r) return 0;
      return wp.category.price_type === 'PER_PERSON' && plannedGuests ? r * plannedGuests : r;
    };

    const formatCurrency = (value: number): string => {
      return new Intl.NumberFormat(locale === 'es' ? 'es-ES' : 'en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      }).format(value);
    };

    let totalBudgeted = 0;
    let totalReal = 0;
    let totalPaid = 0;

    for (const wp of weddingProviders) {
      const paid = wp.payments.reduce((sum: number, p: any) => sum + Number(p.amount), 0);
      totalBudgeted += getProjected(wp);
      totalReal += getRealTotal(wp);
      totalPaid += paid;
    }

    const styles = StyleSheet.create({
      page: {
        padding: 40,
        fontSize: 10,
        fontFamily: 'Helvetica',
      },
      header: {
        marginBottom: 30,
        borderBottomWidth: 2,
        borderBottomColor: '#e5e7eb',
        paddingBottom: 15,
        display: 'flex',
        flexDirection: 'row',
      },
      headerContent: {
        flex: 1,
      },
      logo: {
        width: 60,
        height: 60,
        marginRight: 20,
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 5,
      },
      subtitle: {
        fontSize: 12,
        color: '#6b7280',
      },
      section: {
        marginBottom: 25,
      },
      sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 10,
        backgroundColor: '#f3f4f6',
        padding: 8,
      },
      tableHeader: {
        backgroundColor: '#374151',
        color: '#ffffff',
        fontWeight: 'bold',
      },
      tableRow: {
        display: 'flex',
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
      },
      tableRowAlt: {
        backgroundColor: '#f9fafb',
      },
      tableCell: {
        padding: 8,
        fontSize: 9,
        flex: 1,
      },
      tableCellRight: {
        textAlign: 'right' as const,
      },
      totalsRow: {
        fontWeight: 'bold',
        backgroundColor: '#e0e7ff',
        color: '#1e1b4b',
      },
      footer: {
        marginTop: 40,
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        textAlign: 'center' as const,
        color: '#9ca3af',
        fontSize: 9,
      },
    });

    const tableRows = weddingProviders.map((wp: any, index: number) => {
      const paid = wp.payments.reduce((sum: number, p: any) => sum + Number(p.amount), 0);
      const total = getRealTotal(wp);
      const projected = getProjected(wp);
      const pending = total - paid;

      return React.createElement(View, { key: wp.id, style: [styles.tableRow, index % 2 === 1 && styles.tableRowAlt] },
        React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
          React.createElement(Text, null, wp.category.name)
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
          React.createElement(Text, null, wp.name || wp.provider?.name || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
          React.createElement(Text, null, wp.contact_name || wp.provider?.contact_name || '')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
          React.createElement(Text, null, wp.budgeted_price ? formatCurrency(Number(wp.budgeted_price)) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
          React.createElement(Text, null, projected > 0 ? formatCurrency(projected) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
          React.createElement(Text, null, total > 0 ? formatCurrency(total) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
          React.createElement(Text, null, paid > 0 ? formatCurrency(paid) : '—')
        ),
        React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
          React.createElement(Text, null, pending > 0 ? formatCurrency(pending) : '—')
        )
      );
    });

    const PDFDoc = React.createElement(Document, null,
      React.createElement(Page, { size: 'A4', style: styles.page },
        logoUrl
          ? React.createElement(View, { style: styles.header },
              React.createElement(PDFImage, { src: logoUrl, style: styles.logo }),
              React.createElement(View, { style: styles.headerContent },
                React.createElement(Text, { style: styles.title }, t('exportWeddingProviders') || 'Wedding Providers'),
                React.createElement(Text, { style: styles.subtitle }, new Date().toLocaleDateString()),
                plannedGuests > 0 && React.createElement(Text, { style: styles.subtitle }, `${t('plannedGuests') || 'Planned Guests'}: ${plannedGuests}`)
              )
            )
          : React.createElement(View, { style: styles.header },
              React.createElement(Text, { style: styles.title }, t('exportWeddingProviders') || 'Wedding Providers'),
              React.createElement(Text, { style: styles.subtitle }, new Date().toLocaleDateString()),
              plannedGuests > 0 && React.createElement(Text, { style: styles.subtitle }, `${t('plannedGuests') || 'Planned Guests'}: ${plannedGuests}`)
            ),

        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, t('exportWeddingProviders') || 'Wedding Providers'),

          React.createElement(View, { style: { ...styles.section, marginBottom: 0 } },
            React.createElement(View, { style: [styles.tableRow, styles.tableHeader] },
              React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
                React.createElement(Text, null, t('category') || 'Category')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
                React.createElement(Text, null, t('provider') || 'Provider')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
                React.createElement(Text, null, t('contactPerson') || 'Contact')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('budgetedPrice') || 'Budgeted')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('projectedTotal') || 'Projected')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('totalPrice') || 'Total')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('paid') || 'Paid')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, t('pending') || 'Pending')
              )
            ),
            ...tableRows,
            React.createElement(View, { style: [styles.tableRow, styles.totalsRow] },
              React.createElement(View, { style: [styles.tableCell, { flex: 1.5 }] },
                React.createElement(Text, null, t('totals') || 'Totals')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 2 }] },
                React.createElement(Text, null, '')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1 }] },
                React.createElement(Text, null, '')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, '')
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalBudgeted))
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1.2, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalReal))
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalPaid))
              ),
              React.createElement(View, { style: [styles.tableCell, { flex: 1, ...styles.tableCellRight }] },
                React.createElement(Text, null, formatCurrency(totalReal - totalPaid))
              )
            )
          )
        ),

        React.createElement(View, { style: styles.footer },
          React.createElement(Text, null, footer)
        )
      )
    );

    const buffer = await renderToBuffer(PDFDoc);

    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="wedding-providers-${new Date().toISOString().split('T')[0]}.pdf"`,
      },
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
